#!/usr/local/bin/fish
# rm one.zip

zip -r one.zip index.js hello.rb hello-1.0.0-linux-x86_64

aws lambda update-function-code --region us-west-2 --profile aklambda --function-name ruby --zip-file fileb://one.zip

# aws lambda create-function --region us-west-2 --runtime nodejs4.3 --role arn:aws:iam::268578439486:role/service-role/slackGoogleRole --profile aklambda --function-name ruby --handler index.handler --zip-file fileb://one.zip
